In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Task 1
# A and B
df1 = pd.read_csv('Lab2 D1A.csv')
df2 = pd.read_csv('Lab2 D1B.csv')
df3 = pd.read_csv('Lab2 D1C.csv')


comboAB = df1.merge(df2)
print(comboAB.columns)
print(comboAB.shape)

# C
comboAC = df1.merge(df3)
print(comboAC.shape)

Index(['fid', 'name', 'population', 'county', 'latitude', 'longitude', 'level',
       'enrollment', 'level.1'],
      dtype='object')
(27033, 9)
(4221333, 7)

In [4]:
# Task 2
# A
import random
customizedData = pd.DataFrame(
    {
    'county': comboAB['county'],
    'size' : [random.choice(['small','medium','high']) for _ in range(27033)],
    'cardinal direction' : [random.choice(['north','south','east','west']) for _ in range(27033)],
    'timings' : [random.choice(['full time','part time']) for _ in range(27033)],
    'department' : [random.choice(['IT','HR','Marketing']) for _ in range(27033)],
    'salary' : [random.randint(10000,100000) for _ in range(27033)]
    }
)
# print(customizedData)

# B
merge_df1_df2 = df2.merge(df1)
modifiedData = customizedData.merge( merge_df1_df2)
print(modifiedData)

           county   size cardinal direction    timings department  salary  \
0         BRISTOL   high               east  part time         HR   60654
1         BRISTOL   high               east  part time         HR   60654
2         BRISTOL   high               east  part time         HR   60654
3         BRISTOL   high               east  part time         HR   60654
4         BRISTOL   high               east  part time         HR   60654
...           ...    ...                ...        ...        ...     ...
4249888  WAUSHARA  small               east  full time  Marketing   45844
4249889  WAUSHARA  small               east  full time  Marketing   45844
4249890  WAUSHARA  small               east  full time  Marketing   45844
4249891  WAUSHARA  small               east  full time  Marketing   45844
4249892  WAUSHARA  small               east  full time  Marketing   45844

                                               name  population  longitude  \
0                     NEW ENGLAND CHRISTIAN ACADEMY         136 -71.175801
1                           SETON ACADEMY FOR GIRLS          57 -71.147302
2        NATIVITY PREPARATORY SCHOOL OF NEW BEDFORD          62 -70.926852
3                         ST MARY'S CATHOLIC SCHOOL         233 -71.202492
4                                             AMEGO          24 -71.240718
...                                             ...         ...        ...
4249888                   OAKRIDGE MENNONITE SCHOOL          31 -89.141192
4249889                      CHRIST LUTHERAN SCHOOL          30 -88.972904
4249890                   ST JOHN'S LUTHERAN SCHOOL          24 -88.886093
4249891                     FAITH CHRISTIAN ACADEMY          13 -89.294984
4249892                           SHADY PINE SCHOOL          17 -89.377692

                                     level  enrollment  \
0        Combined elementary and secondary         120
1                               Elementary          49
2                               Elementary          54
3                               Elementary         219
4        Combined elementary and secondary          19
...                                    ...         ...
4249888                         Elementary          28
4249889                         Elementary          27
4249890                         Elementary          22
4249891                         Elementary          11
4249892                         Elementary          16

                                   level.1    fid   latitude
0        Combined elementary and secondary   9001  41.758597
1                               Elementary   9002  41.718407
2                               Elementary   9006  41.633263
3                               Elementary   9009  42.035372
4        Combined elementary and secondary   9013  42.012844
...                                    ...    ...        ...
4249888                         Elementary  20244  44.067848
4249889                         Elementary  20252  44.210772
4249890                         Elementary  20998  44.202182
4249891                         Elementary  20999  44.074503
4249892                         Elementary  21000  44.014975

[4249893 rows x 14 columns]

In [ ]:
# # task 3
# # A and B
train = pd.read_csv('train.csv')

# # C
# # corrs = ['var3','var15','var38','imp_op_var39_comer_ult1']
# # plt.figure(figsize=(12,7))
# # check = train[corrs]
# # sns.heatmap(data = check.corr(),annot=True)
# # plt.show()

# # D,E
# # target = 'TARGET'  

# # for col in train.drop(columns=[target]).columns:
# #     plt.scatter(train[col], train[target])
# #     plt.xlabel(col)
# #     plt.ylabel(target)
# #     plt.title(f"{col} vs {target}")
# #     plt.show()
# train.head()

# # F

# # corr = ["var3","var15","imp_ent_var16_ult1","imp_op_var39_comer_ult1","imp_op_var39_comer_ult3"]
# # sns.heatmap(train[corr].corr(), annot=True, cmap="coolwarm")
# # plt.title("Correlation Heatmap")
# # plt.show()

# # G,H

# # from sklearn.utils import resample

# # print(train['TARGET'].value_counts())

# # resampled = resample(train[train['TARGET'] == 1],replace=True,n_samples=len(train[train['TARGET'] == 0]))       

# # balanced = pd.concat([train[train['TARGET'] == 0],resampled])

# # print(balanced['TARGET'].value_counts())

# # I

# # features = train.shape[1] - 1 # Excluded target column
# # records = train.shape[0]
# # print(f"Number of features: {features}")
# # print(f"Number of records: {records}")

correlation = train.corr()['target'].abs()# Pearson correlation

threshold = 0.65
selected_features = correlation[correlation > threshold].drop('target')
print(selected_features)

train_selected = train[selected_features + ['TARGET']]
train_selected.head()

# J

copied_train = train.copy()

X = copied_train.drop('target', axis=1)
mad = (X - X.mean()).abs().mean()
top_mad = mad.nlargest(10)

print(f"\nTop 10 features by Mean Absolute Deviation:")
print(top_mad)

0

   TARGET
0       0
1       0
2       0
3       0
4       0

In [ ]:
dt = pd.read_csv("heart.csv")

# C

# dt.describe()
# sns.boxplot(x="target", y="age", data=dt)
# plt.show()
# sns.boxplot(x="target", y="sex", data=dt)
# plt.show()

# D

# dt.isnull().sum()

# E

# print(dt['target'].value_counts())

# from sklearn.utils import resample

# majority = dt[dt['target'] == 1]
# minority = dt[dt['target'] == 0]

# resampled_minority = resample(minority, replace=True, n_samples=len(majority), random_state=42)

# balanced_dt = pd.concat([majority, resampled_minority])

# print(balanced_dt['target'].value_counts())

# F

# copied = dt.copy()

# X = copied.drop('target', axis=1)
# mad = (X - X.mean()).abs().mean()
# top_mad = mad.nlargest(10)

# print(f"\nTop 10 features by Mean Absolute Deviation:")
# print(top_mad)

# G

# My dataset have no catagorical features. The differnece between one hot encoding and dummy encoding is that one hot encoding creates a new
# binary column for each category in the original column, while dummy encoding creates k-1 binary columns for a categorical variable with k
# categories.

# H

print(dt.duplicated().sum())

# dt.drop_duplicates()

# dt.drop_duplicates(subset=['Name'], keep='first')

723